### ISSUE TITLE
Performance improvements

### ISSUE THREAD

**Issue by HoshiYamazaki** [kaueraal/run_scaled#17]
I know that run_scaled is temporary solution until Xwayland will works fine, but for now - it works horribly slow even if I have OpenGL enabled. 
I ran game called NosTale under Wine and performance is sooo slow. Like I ran it inside VM despite having powerfull PC (i5-6600, rx480 4GB, 16GB ram).

**Comment by kaueraal** [comment]
This is nothing which can be fixed with the current approach. Proper performance for games requires the scaling at a completely different layer, way, way out of the scope of the project.

Sorry for the bummer, but this really requires support by some deeper rendering layer. Even the approach of #20 would be way to slow for games.

**Comment by totaam** [comment]
> Even the approach of #20 would be way to slow for games.
It depends: VirtualGL is very close to native speed, then xpra has to copy the pixels from the virtual screen to the real one, via CPU memory and mmap, this does take time.
It really depends on the resolution, and the type of game.
If OpenGL is the bottleneck and the extra latency is not a huge problem, this works well.
(input devices is another problem entirely..)
