### ISSUE TITLE
[Idea request] Do run_scaled via virtualgl + vnc

### ISSUE THREAD

**Issue by PSzczepanski1996** [kaueraal/run_scaled#20]
I know that it's possible but or I am messing configuration, or it does not launch at 90% of cases.
Still I managed to run old game Nostale in VNC server so it's great solution for temporary scaling.
Configuration is pain in the ass though.

**Comment by kaueraal** [comment]
Sorry, I absolutely don't understand your text. Please formulate more clearly what you want/what your issue is.

**Comment by HoshiYamazaki** [comment]
Ok, my issue text was messy because I was in manic state ;) It's idea request.
So, VirtualGL provides hardware graphics acceleration which is useful in games (for example - Wine). Wine does not provide solution to scale apps, nor many other applications do.
Instead of using XPRA which is slow as hell (it uses CPU rendering? I don't know), you could use VirtualGL, running VNC server inside and launch on current host (xorg) VNC Client with scaling like Remmina.
I think it's great solution TODO but it's hard to configure (for me).

See this:
https://wiki.archlinux.org/index.php/VirtualGL
https://remmina.org/

You could use another VNC Client but I don't know which are supporting scaling.
And sorry for bad english.

**Comment by HoshiYamazaki** [comment]
The whole problem is that run_scaled works fine for basic 2D apps, but only for them.
This is my (maybe temporary) solution.

**Comment by kaueraal** [comment]
VNC would be most likely to slow as well, but maybe there's some other way with VirtualGL.

**Comment by totaam** [comment]
xpra supports virtualgl just fine, try `xpra start --exec-wrapper="vglrun -d :1" --start=whatever`

**Comment by kaueraal** [comment]
Xpra directly includes an equivalent tool since [version 4.1](https://github.com/Xpra-org/xpra/blob/4d73c3644d6692bd51376296ed913f18a809f1a9/docs/CHANGELOG.md#41-2021-02-26). It is also called `run_scaled` and is part of [the default Xpra installation](https://github.com/Xpra-org/xpra/blob/master/fs/bin/run_scaled).

Hence, this script here is deprecated and no longer maintained. I'm sorry that it took me quite long to officially announce it here. Thank you for your support and please continue your HiDPI journey with Xpra's tool!
