### ISSUE TITLE
Running script as sudo will cause login issues

### ISSUE THREAD

**Issue by MauroFoti** [kaueraal/run_scaled#23]
If you run `pkexec run_scaled application`, it will generate cause the file `~/.Xauthority` to have root ownership.
This will make impossible to login to a user using lightdm unless the ownership of the file is restored.

**Comment by kaueraal** [comment]
Running X11 applications as root opens a large can of worms and the issue described hasn't really to do anything with run_scaled.

This concrete issues most likely happens, because pkexec retains most of your environment variables, including your home directory. Depending on the application you're running the same thing will also happen to other files written by the target application.

In case you are really sure you still want to do that (again, this is usually a bad idea), you can try some other approach. `sudo -H` should work, as switching `pkexec` and `run_scaled` around to `run_scaled pkexec application`.
