### ISSUE TITLE
[Solved] xpra deleting printers

### ISSUE THREAD

**Issue by Uatschitchun** [kaueraal/run_scaled#24]
Hi. I'm running run_scaled on 18.04. 
Since some update to xpra I had the issue that quitting a program started with run_scaled xpra deletes my printers ;(
I added --printing=no to "xpra start" in run_scaled and solved the issue 

Just wanted to let you know

**Comment by totaam** [comment]
[Existing local printers deleted on server exit
](https://xpra.org/trac/ticket/2095)

**Comment by jefferysmall** [comment]
Uatschitchun, thanks for tracking this down. I was having the identical problem with my cups printer configuration on my Xubuntu 19.04 system.  Just made this change and so far it seems to have fixed things.

The current packaged version of xpra is 2.4.3+dfsg1 so this doesn't appear to have the xpra bug fix that was incorporated six months ago.

**Comment by totaam** [comment]
The Debian / Ubuntu packages _never_ get any bug fixes (not even crasher bugs or security issues):
https://xpra.org/trac/wiki/Packaging/DistributionPackages

**Comment by kaueraal** [comment]
Xpra directly includes an equivalent tool since [version 4.1](https://github.com/Xpra-org/xpra/blob/4d73c3644d6692bd51376296ed913f18a809f1a9/docs/CHANGELOG.md#41-2021-02-26). It is also called `run_scaled` and is part of [the default Xpra installation](https://github.com/Xpra-org/xpra/blob/master/fs/bin/run_scaled).

Hence, this script here is deprecated and no longer maintained. I'm sorry that it took me quite long to officially announce it here. Thank you for your support and please continue your HiDPI journey with Xpra's tool!
