### ISSUE TITLE
using sleep is a bad idea

### ISSUE THREAD

**Issue by totaam** [kaueraal/run_scaled#25]
Race conditions, etc.
Try `xpra start --start=whatever --attach=yes`

This will start a server and attach when it is ready.

**Comment by kaueraal** [comment]
Xpra directly includes an equivalent tool since [version 4.1](https://github.com/Xpra-org/xpra/blob/4d73c3644d6692bd51376296ed913f18a809f1a9/docs/CHANGELOG.md#41-2021-02-26). It is also called `run_scaled` and is part of [the default Xpra installation](https://github.com/Xpra-org/xpra/blob/master/fs/bin/run_scaled).

Hence, this script here is deprecated and no longer maintained. I'm sorry that it took me quite long to officially announce it here. Thank you for your support and please continue your HiDPI journey with Xpra's tool!
