### ISSUE TITLE
Very slow start-up

### ISSUE THREAD

**Issue by jefferysmall** [kaueraal/run_scaled#28]
I saw the question regarding slow game performance, but I'm having slow start-ups in the order of 6-9 seconds for various programs. I do see and understand the lag during operation of graphic-intensive programs, but is the start-up delay normal for simple X11 programs like xfontsel?  If so, no problem, but I wanted to check that I wasn't missing something that might improve loading speed.  Thanks.

**Comment by totaam** [comment]
xpra will start a vfb to run the X11 application, this can take several seconds and is out of our control.
xpra 3.0 will have faster startup:
https://xpra.org/trac/ticket/2341

In the meantime, you may want to change your xpra configuration to use Xvfb instead of Xdummy (assuming that your default config uses Xdummy)

**Comment by kaueraal** [comment]
Xpra directly includes an equivalent tool since [version 4.1](https://github.com/Xpra-org/xpra/blob/4d73c3644d6692bd51376296ed913f18a809f1a9/docs/CHANGELOG.md#41-2021-02-26). It is also called `run_scaled` and is part of [the default Xpra installation](https://github.com/Xpra-org/xpra/blob/master/fs/bin/run_scaled).

Hence, this script here is deprecated and no longer maintained. I'm sorry that it took me quite long to officially announce it here. Thank you for your support and please continue your HiDPI journey with Xpra's tool!
