### ISSUE TITLE
Integer scale to avoid blur?

### ISSUE THREAD

**Issue by mhtvsSFrpHdE** [kaueraal/run_scaled#29]
If scale factor is 2, then a integer scale can produce sharp good results.  
The default scale is blur.

**Comment by w-barath** [comment]
adding --opengl=no to the xpra args might help.

**Comment by w-barath** [comment]
Hmm... tried replacing all `GL_LINEAR` with `GL_NEAREST` for function `glTexParameteri()` in the `client/gl/gl_window_backing_base.py` file and removing all the .pyc files, and it had no effect on Intel 520 graphics.   Maybe someone else has an idea.

**Comment by Zom-B** [comment]
I have the same issue, that I don't want to see it blurred when scaling is 2.

**Comment by kaueraal** [comment]
Xpra directly includes an equivalent tool since [version 4.1](https://github.com/Xpra-org/xpra/blob/4d73c3644d6692bd51376296ed913f18a809f1a9/docs/CHANGELOG.md#41-2021-02-26). It is also called `run_scaled` and is part of [the default Xpra installation](https://github.com/Xpra-org/xpra/blob/master/fs/bin/run_scaled).

Hence, this script here is deprecated and no longer maintained. I'm sorry that it took me quite long to officially announce it here. Thank you for your support and please continue your HiDPI journey with Xpra's tool!
