### ISSUE TITLE
Mouse cursor not scaled, but scaled ;)

### ISSUE THREAD

**Issue by Uatschitchun** [kaueraal/run_scaled#30]
Hi, I've got the problem that my mouse cursor isn't scaled well. It is quite large ;(
![Screenshot_20191015_182423](https://user-images.githubusercontent.com/25088926/66850518-476e4100-ef79-11e9-96d4-73a3c57b0f5a.png)

Any way to scale it down appropriately?

**Comment by Uatschitchun** [comment]
No way to keep cursor unscaled?

**Comment by kaueraal** [comment]
Xpra directly includes an equivalent tool since [version 4.1](https://github.com/Xpra-org/xpra/blob/4d73c3644d6692bd51376296ed913f18a809f1a9/docs/CHANGELOG.md#41-2021-02-26). It is also called `run_scaled` and is part of [the default Xpra installation](https://github.com/Xpra-org/xpra/blob/master/fs/bin/run_scaled).

Hence, this script here is deprecated and no longer maintained. I'm sorry that it took me quite long to officially announce it here. Thank you for your support and please continue your HiDPI journey with Xpra's tool!
