### ISSUE TITLE
Forego xpra dependency 

### ISSUE THREAD

**Issue by MarkJeronimus** [kaueraal/run_scaled#34]
I can't install xpra because some package it depends on has incorrect dependencies listed in bionic.
That dependency needs `xserver-xorg-core` 2:1.18.something but I have `xserver-xorg-core-hwe-18.04` 2:1.20.something.

Is there a way to use this script without xpra?

I found this: https://bugs.launchpad.net/ubuntu/+source/xpra/+bug/1691025
I confirmed that trying to manually install `xserver-xorg-core` will remove lots of packages, so I'm not going to do that.

**Comment by guss77** [comment]
Have you tried to use the xpra.org packages as commented in [that bug report in comment 7](https://bugs.launchpad.net/ubuntu/+source/xpra/+bug/1691025/comments/7) ?

**Comment by MarkJeronimus** [comment]
Same thing. It will remove lots of xserver-xorg packages, and I don't want to risk breaking my distro.

**Comment by Zom-B** [comment]
I tried it again (still on bionic) and this time it didn't want to uninstall packages, and the script works. You can close this as 'works for me'.

**Comment by MarkJeronimus** [comment]
I tried it again (still on bionic) and this time it didn't want to uninstall packages, and the script works. You can close this as 'works for me'.

**Comment by kaueraal** [comment]
Xpra directly includes an equivalent tool since [version 4.1](https://github.com/Xpra-org/xpra/blob/4d73c3644d6692bd51376296ed913f18a809f1a9/docs/CHANGELOG.md#41-2021-02-26). It is also called `run_scaled` and is part of [the default Xpra installation](https://github.com/Xpra-org/xpra/blob/master/fs/bin/run_scaled).

Hence, this script here is deprecated and no longer maintained. I'm sorry that it took me quite long to officially announce it here. Thank you for your support and please continue your HiDPI journey with Xpra's tool!
