### ISSUE TITLE
Breakage if using non-default "bc" settings

### ISSUE THREAD

**Issue by vstax** [kaueraal/run_scaled#37]
Hello. Thanks for this neat script.

I've tried it yesterday for the first time and it didn't work for me: turns out, it assumes that bc has 0 digit precision, which is default but might not always be the case.
I use bc a lot and have `~/.bcrc` with following contents
```
scale = 3
```

This makes run_scaled break like this (for 4K screen):
```
(EE) Invalid screen configuration 1920.000x1080.000x24+32 for -screen 0
```

The solution is trivial though a bit ugly, calculate unscaled resolution as follows
```
UNSCALED_RESOLUTION="$( bc <<<"scale=0; $UNSCALED_RESOLUTION_X / $SCALING_FACTOR" )x$( bc <<<"scale=0; $UNSCALED_RESOLUTION_Y / $SCALING_FACTOR" )"
```
It's unfortunate that there are no better options such as "skip reading RC file", but that's how it is.

I also wish it would fail more gracefully in absence of dependencies, e.g I saw that xpra is required but script was failing in not very obvious until I installed Xvfb as well. But, well, that's a different issue :)

**Comment by devkev** [comment]
I also have `scale` set in my `.bcrc`.  I created PR #41 to fix it.

**Comment by kaueraal** [comment]
Xpra directly includes an equivalent tool since [version 4.1](https://github.com/Xpra-org/xpra/blob/4d73c3644d6692bd51376296ed913f18a809f1a9/docs/CHANGELOG.md#41-2021-02-26). It is also called `run_scaled` and is part of [the default Xpra installation](https://github.com/Xpra-org/xpra/blob/master/fs/bin/run_scaled).

Hence, this script here is deprecated and no longer maintained. I'm sorry that it took me quite long to officially announce it here. Thank you for your support and please continue your HiDPI journey with Xpra's tool!
