### ISSUE TITLE
Undocumented dependencies

### ISSUE THREAD

**Issue by hosford42** [kaueraal/run_scaled#38]
I had to install several undocumented dependencies before this script worked for me:

- xpra: `sudo apt install xpra`
- uinput: `sudo pip3 install python-uinput`
- xvfb: `sudo apt install xvfb`

At least they are documented here, now, but it would be better if they were mentioned in the README.

**Comment by tve** [comment]
ditto
on arch for xvfb it was xorg-server-xvfb
I really would have appreciated if all this was mentioned in the readme where I would have seen it, would have saved me a bunch of time!

**Comment by totaam** [comment]
`uinput` is not needed, and if it was then it should not be installed via pip.

`xvfb` should have been installed as a dependency when you installed `xpra`.

So the only dependency you really need is `xpra`, and as of version 4.1 the `run_scaled` script is included in the package.

**Comment by bkerin** [comment]
xvfb was also not installed as a dependency for me, and error messages just said "failed to connect to server" or so, I would never have figured it out without this issue report.

**Comment by bkerin** [comment]
on mint linux 20

**Comment by kaueraal** [comment]
Xpra directly includes an equivalent tool since [version 4.1](https://github.com/Xpra-org/xpra/blob/4d73c3644d6692bd51376296ed913f18a809f1a9/docs/CHANGELOG.md#41-2021-02-26). It is also called `run_scaled` and is part of [the default Xpra installation](https://github.com/Xpra-org/xpra/blob/master/fs/bin/run_scaled).

Hence, this script here is deprecated and no longer maintained. I'm sorry that it took me quite long to officially announce it here. Thank you for your support and please continue your HiDPI journey with Xpra's tool!
