### ISSUE TITLE
apps menu not appearing

### ISSUE THREAD

**Issue by chapochn** [kaueraal/run_scaled#4]
Hi,
When i run in the terminal
./run_scaled app_name
the apps menus in the top menu bar are not appearing (like file, edit, etc...), would you know how to fix that?
xpra version: v2.0.2-r15657
Ubuntu 16.04, Unity desktop

I found this:
https://www.xpra.org/trac/ticket/1419
https://www.xpra.org/trac/wiki/FAQ?action=diff&version=74
but not sure if it is relevant and how to incorporate it in your code

Many thanks!

**Comment by kaueraal** [comment]
Unfortunatly the fix mentioned there does not work, at least with my Ubuntu I just installed. I opened a bug for it: https://xpra.org/trac/ticket/1512

**Comment by Chachni** [comment]
Ok, thanks for checking out! So you would say it is an Ubuntu bug then?

**Comment by kaueraal** [comment]
Probably. run_scaled should use the --start=-flag of xpra instead of starting the applications itself, as mentioned in your linked documentation, but in recent Ubuntu version stuff breaks anyways.

**Comment by Chachni** [comment]
running
`UBUNTU_MENUPROXY=0 ./run_scaled app_name`
works for most programs, apart from libreoffice.
Output for xournal (for which it works) and impress (for which it doesn't).
[xournal.txt](https://github.com/kaueraal/run_scaled/files/1300849/xournal.txt)
[impress.txt](https://github.com/kaueraal/run_scaled/files/1300850/impress.txt)

Any ideas?

**Comment by kaueraal** [comment]
Xpra directly includes an equivalent tool since [version 4.1](https://github.com/Xpra-org/xpra/blob/4d73c3644d6692bd51376296ed913f18a809f1a9/docs/CHANGELOG.md#41-2021-02-26). It is also called `run_scaled` and is part of [the default Xpra installation](https://github.com/Xpra-org/xpra/blob/master/fs/bin/run_scaled).

Hence, this script here is deprecated and no longer maintained. I'm sorry that it took me quite long to officially announce it here. Thank you for your support and please continue your HiDPI journey with Xpra's tool!
