### ISSUE TITLE
`run_scaled` can't find the target to run

### ISSUE THREAD

**Issue by Heimdell** [kaueraal/run_scaled#40]
I'm attempring to run Diablo II under wine, upscaled.

I use `wine PlugY` to run it normally.

Yet, when I do `run_scaled --scale=2 wine PlugY`, I get:
```
2021-03-22 14:43:20,346 Error spawning child '"wine PlugY"':
2021-03-22 14:43:20,346  [Errno 2] No such file or directory: 'wine PlugY'
```

P.S.: absolute paths do not work either:
```
2021-03-22 14:48:01,802 Error spawning child '"/usr/bin/gedit"':
2021-03-22 14:48:01,802  [Errno 2] No such file or directory: '/usr/bin/gedit'
```

**Comment by guss77** [comment]
@Heimdell - are you using run_scaled from this repo, or xpra's (now builtin) run_scaled? If its the former - can you run it with `bash -x` and show the output? If its the latter - can you upload the full log file?

**Comment by Heimdell** [comment]
I was using `xpra`-one, thinking I'm using your one.
[:1.log](https://github.com/kaueraal/run_scaled/files/6189498/1.log)

I tried your one:
[:57158215.log](https://github.com/kaueraal/run_scaled/files/6189507/57158215.log)

Sadly, it did not run anything as well.

I tried with `gedit` for no luck:
[:27467509.log](https://github.com/kaueraal/run_scaled/files/6189516/27467509.log)

**Comment by totaam** [comment]
@Heimdell my bad, sorry. The fix is trivial:
https://github.com/Xpra-org/xpra/commit/deb31610ea3ecc684ee0861dc258b1384e18aa0e#diff-dce7cce055566bed799f788cd0048e209a27a473c0f48b956fa1f1780e80d2c1

So you can easily apply it to your installation (edit `/usr/bin/run_scaled` by hand) until xpra 4.1.2 is released, or you can also run `run_scaled xterm` and then run whatever you want from there instead.

**Comment by kaueraal** [comment]
Xpra directly includes an equivalent tool since [version 4.1](https://github.com/Xpra-org/xpra/blob/4d73c3644d6692bd51376296ed913f18a809f1a9/docs/CHANGELOG.md#41-2021-02-26). It is also called `run_scaled` and is part of [the default Xpra installation](https://github.com/Xpra-org/xpra/blob/master/fs/bin/run_scaled).

Hence, this script here is deprecated and no longer maintained. I'm sorry that it took me quite long to officially announce it here. Thank you for your support and please continue your HiDPI journey with Xpra's tool!
