### ISSUE TITLE
use run_scaled to front end whole desktop

### ISSUE THREAD

**Issue by cjns1989** [kaueraal/run_scaled#43]
Gave run_scaled a shot with a Tetris clone called ltris on a 4K@60 screen with good results. Hardly could tell the difference.

I'm currently running ubuntu 2104+gnome 3 (ouch...) but I was wondering if one could use run_scaled to front-end a minimal desktop such as **Window Maker** (an old time favorite of mine that 's never failed me) hopefully scaling the graphics of all its subprocesses by the specified scale factor. 

Not that playing ltris is to be frowned upon… but where I am concerned that would be really useful!

Before I get my hopes too high… would that be likely to work?

Considering Window Maker doesn't use any fancy special effects and does its stuff with minimal resources I cannot see why it shouldn't.

Has anyone experimented with that or something similar with another so-called 'window manager'?

**Comment by kaueraal** [comment]
Xpra directly includes an equivalent tool since [version 4.1](https://github.com/Xpra-org/xpra/blob/4d73c3644d6692bd51376296ed913f18a809f1a9/docs/CHANGELOG.md#41-2021-02-26). It is also called `run_scaled` and is part of [the default Xpra installation](https://github.com/Xpra-org/xpra/blob/master/fs/bin/run_scaled).

Hence, this script here is deprecated and no longer maintained. I'm sorry that it took me quite long to officially announce it here. Thank you for your support and please continue your HiDPI journey with Xpra's tool!
