### ISSUE TITLE
xpra local latency

### ISSUE THREAD

**Issue by stream-punk** [kaueraal/run_scaled#44]
I found out that `--av-sync=no` make a huge difference in latency and I think `--keyboard-sync=no` also improves the experience a bit. But of course it depends on the use-case. For video it would worsen the experience.

**Comment by totaam** [comment]
@davidsonder `av-sync` should be disabled unless your application does use audio *and* you have speaker forwarding enabled.
But due to bugs, this was not the case. Both issues will be fixed in the 4.3 release.

**Comment by kaueraal** [comment]
Xpra directly includes an equivalent tool since [version 4.1](https://github.com/Xpra-org/xpra/blob/4d73c3644d6692bd51376296ed913f18a809f1a9/docs/CHANGELOG.md#41-2021-02-26). It is also called `run_scaled` and is part of [the default Xpra installation](https://github.com/Xpra-org/xpra/blob/master/fs/bin/run_scaled).

Hence, this script here is deprecated and no longer maintained. I'm sorry that it took me quite long to officially announce it here. Thank you for your support and please continue your HiDPI journey with Xpra's tool!
