### ISSUE TITLE
Some apps do not start after using run_scaled

### ISSUE THREAD

**Issue by imirzov** [kaueraal/run_scaled#47]
Hi and thank you for the script!
I've found out that after using run_scaled some applications do not start on my Ubuntu 22.04 with Gnome 42.4.
For example, I can not run terminal and gedit neither from applications menu nor with hotkeys. But after logging out and signing in again everything is OK. How to fix it?

**Comment by Reocin** [comment]
Same here!

**Comment by kaueraal** [comment]
Xpra directly includes an equivalent tool since [version 4.1](https://github.com/Xpra-org/xpra/blob/4d73c3644d6692bd51376296ed913f18a809f1a9/docs/CHANGELOG.md#41-2021-02-26). It is also called `run_scaled` and is part of [the default Xpra installation](https://github.com/Xpra-org/xpra/blob/master/fs/bin/run_scaled).

Hence, this script here is deprecated and no longer maintained. I'm sorry that it took me quite long to officially announce it here. Thank you for your support and please continue your HiDPI journey with Xpra's tool!
