### ISSUE TITLE
Some apps don't run successfully with child with pid has terminated message

### ISSUE THREAD

**Issue by axelson** [kaueraal/run_scaled#48]
I have `run_scaled` mostly working and programs like xev, xmessage, and gnome-calculator successfully run. However some programs such as gnome-terminal and ynab4 immediately exit and then the server shuts down. When this happens I see the following in the in my xpra logs:

> 2023-03-11 20:13:44,074 child 'gnome-terminal ' with pid 32164 has terminated
> 2023-03-11 20:13:44,074 all children have exited and --exit-with-children was specified, exiting
> 2023-03-11 20:13:44,074 Disconnecting client /run/user/1000/xpra/linux-mint-desktop-70894022:
> 2023-03-11 20:13:44,074  server shutdown

However, if I change 
> xpra start "$DISPLAYNUM" --xvfb="Xvfb +extension Composite -screen 0 ${UNSCALED_RESOLUTION}x24+32 -nolisten tcp -noreset  -auth \$XAUTHORITY" --env=GDK_SCALE=1 --env=GDK_DPI_SCALE=1 --start-child="$ESCAPED_PARAMS" --exit-with-children

to:
> xpra start "$DISPLAYNUM" --xvfb="Xvfb +extension Composite -screen 0 ${UNSCALED_RESOLUTION}x24+32 -nolisten tcp -noreset  -auth \$XAUTHORITY" --env=GDK_SCALE=1 --env=GDK_DPI_SCALE=1 --start-child="$ESCAPED_PARAMS"

Then the programs successfully run! But of course after they close xpra/run_scaled is still running to I need to manually close it.

Just sharing in case it is helpful for someone.

Note: I'm running on the current latest version of Linux Mint

**Comment by kaueraal** [comment]
Xpra directly includes an equivalent tool since [version 4.1](https://github.com/Xpra-org/xpra/blob/4d73c3644d6692bd51376296ed913f18a809f1a9/docs/CHANGELOG.md#41-2021-02-26). It is also called `run_scaled` and is part of [the default Xpra installation](https://github.com/Xpra-org/xpra/blob/master/fs/bin/run_scaled).

Hence, this script here is deprecated and no longer maintained. I'm sorry that it took me quite long to officially announce it here. Thank you for your support and please continue your HiDPI journey with Xpra's tool!

**Comment by axelson** [comment]
That's great news! Thanks for the info.
