### ISSUE TITLE
xpra issue

### ISSUE THREAD

**Issue by gegnew** [kaueraal/run_scaled#7]
I'm getting an error with no info anywhere on the internet:

xpra initialization error: no such option: --desktop-scaling

Thoughts?

**Comment by avik-das** [comment]
I encountered the same issue. It turns out the version of `xpra` I had installed was too old:

```
$ xpra --version
xpra v0.15.8
```

This was on Ubuntu 16.04 Xenial Xerus. The fix was to add the official xpra repositories to my system so I could install xpra from those repositories instead of the Ubuntu repositories. [The xpra downloads page](https://xpra.org/trac/wiki/Download), under the Linux section, details how to add the repositories, which will differ based on the distribution you're running.

After upgrading xpra, running `run_scaled` worked.

```
$ xpra --version
xpra v2.2.6-r18968
```

**Comment by xaviervilla** [comment]
@avik-das Thanks for the info. I also had this issue. Since it wasn't very clear how to install the latest version of xpra, I posted the commands I used for Ubuntu 16.04 Xenial Xerus.

```
sudo su -
`(make sure curl is installed first)`
curl https://xpra.org/gpg.asc | apt-key add -
echo "deb https://xpra.org/ xenial main" > /etc/apt/sources.list.d/winswitch.list;
apt-get install -y software-properties-common >& /dev/null;
add-apt-repository universe >& /dev/null;
apt-get update;
apt-get install xpra
```
